# Generated by Django 4.2.13 on 2024-06-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_record_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='birth_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
